# Generated by Django 4.0.4 on 2022-06-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_parents_mothers_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parents',
        ),
        migrations.DeleteModel(
            name='qualifications',
        ),
    ]
