# Generated by Django 4.0.4 on 2022-06-29 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0007_delete_parents_delete_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exam', models.CharField(max_length=256, null=True)),
                ('name_of_institution', models.CharField(max_length=256, null=True)),
                ('month', models.BigIntegerField(null=True)),
                ('year', models.BigIntegerField(null=True)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('no_of_chances', models.BigIntegerField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=256, null=True)),
                ('fathers_occupation', models.CharField(max_length=256, null=True)),
                ('mothers_name', models.CharField(max_length=256, null=True)),
                ('mothers_occupation', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('res_address', models.CharField(max_length=256, null=True)),
                ('official_address', models.CharField(max_length=256, null=True)),
                ('fathers_email_id', models.EmailField(max_length=254, null=True)),
                ('mothers_email_id', models.EmailField(max_length=254, null=True)),
                ('fathers_number', models.BigIntegerField(null=True)),
                ('mothers_number', models.BigIntegerField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
