# Generated by Django 4.0.4 on 2022-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_achievements_school_admission_details_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission_details',
            name='joined_semester',
        ),
        migrations.AddField(
            model_name='profile_student',
            name='joined_semester',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
