# Generated by Django 4.0.4 on 2022-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_admission_details_joined_semester_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sslc_plustwo_mark',
        ),
        migrations.AddField(
            model_name='hostel',
            name='year',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='biology',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='chemistry',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='computer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='english',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='hindi',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='mal',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='maths',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='physics',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
