# Generated by Django 4.0.4 on 2022-07-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_delete_sslc_plustwo_mark_hostel_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name_of_exam',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PLUS TWO', 'PLUS TWO')], max_length=256, null=True),
        ),
    ]
