# Generated by Django 4.0.4 on 2022-07-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_qualification_name_of_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='mark_percentage',
            field=models.FloatField(null=True),
        ),
    ]
