# Generated by Django 4.0.4 on 2022-07-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_local_guardian_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='address',
            new_name='fathers_address',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='res_address',
            new_name='mothers_address',
        ),
    ]
