# Generated by Django 4.0.4 on 2022-07-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_rename_address_parents_fathers_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='no_of_chances',
            field=models.BigIntegerField(null=True),
        ),
    ]
