# Generated by Django 4.0.4 on 2022-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_qualification_no_of_chances'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
