# Generated by Django 4.0.4 on 2022-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_profile_student_is_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='date_of_course',
            field=models.DateField(null=True),
        ),
    ]
